# Note: For external configuration files, the option names use underscores instead of dashes. Example: fail_on_severity
fail_on_severity: high
# Possible values: Any SPDX-compliant license identifiers or expressions from https://spdx.org/licenses/
allow_licenses:
  - 'GPL-3.0'
  - 'BSD-3-Clause'
  - 'MIT'
  - 'Apache-2.0'
# workaround for events other than PR
base_ref: ${{ github.event.pull_request.base.sha || 'main' }}
head_ref: ${{ github.event.pull_request.head.sha || github.ref }}