fail_on_severity: 'low'
fail_on_scopes:
- 'runtime'
- 'development'
- 'unknown'
license_check: true
vulnerability_check: true
comment_summary_in_pr: 'always'
show_openssf_scorecard: true
warn_on_openssf_scorecard_level: 5
# Possible values: Any SPDX-compliant license identifiers or expressions from https://spdx.org/licenses/
allow_licenses:
  - 'MIT'
  - 'Apache-2.0'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'BSD-2-Clause AND BSD-3-Clause'
