[project]
name = "reusable-workflows"
version = "0.0.0"
description = "Repo for mojotech reusable workflows"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
zizmor = [
    "zizmor==1.15.2",
]