name: Container Scan

on:
  workflow_call:
    inputs:
      image_tag_to_scan:
        description: "Desired image tag to scan (0.0.0, main..)"
        required: true
        type: string
      runner_type:
        description: "Desired runner type (ubuntu-latest, ubuntu-latest-m)"
        required: false
        type: string
        default: "ubuntu-latest"
    secrets:
      ghcr_github_token:
        description: 'GITHUB_TOKEN needed for ghcr login'
        required: true

permissions:
  contents: read
  packages: read
  security-events: write
  actions: read

env:
  DOCKER_IMAGE_TAG: ${{ inputs.image_tag_to_scan }}
  GITHUB_REGISTRY: ghcr.io

jobs:
  sanity-check-inputs:
    runs-on: ubuntu-latest
    steps:
    - name: Check input
      run: |
        if [[ "${RUNNER_TYPE}" == "ubuntu-latest" ]]; then
          echo "Running on ubuntu-latest"
        elif  [[ "${RUNNER_TYPE}" == "ubuntu-latest-m" ]]; then
          echo "Running on ubuntu-latest-m"
        else
          echo "Desired runner type not supported."
          exit 1
        fi
      env:
        RUNNER_TYPE: ${{ inputs.runner_type }}
